	<h1>About</h1>
<p>You may wanna know some background info on how QuantumCraft was created so here is sammko and hunterboerner’s side of the story.
<br/>
<br/>
Sammko (derived from github page)
<br/>
<br/>

It all started a few months ago. I decided that I’d like to work on somthing big. A bigger mod than those I made before. I definitely knew that I wanted a tech mod, even though there is a lot of tech mods already. I just needed to think of what it’d be about and the name. So i figured out, that i would have multiple types of energy. the names were:
<br/><br/>
Positronium
<br/>
Radium<br/>
Gammatronium<br/>
Neutrinium<br/>
<br/><br/>
All those are kinda particle / radiation related, so I thought the name Quantum is OK. then i just appended craft and i got a minecraft mod name. I started to work on it, made some blocks, items and renderers. After that, I got kinda frustrated and I took a brake. maybe 1/2 a month. I realised how much helpful it’d be to work with someone else. So i went to the IRCs and asked for people that would like to help me. that way I found DJRaffa. We worked together created the GitHub repo. We started to work on the GUIs and then - java didn’t like us yet again. So we went on the IRCs again and we found hunterb (Theron Boerner). They both were experienced modders but they didn’t actually make anything significant for some time. They watched tutorials and so on and they got back into it. We worked on alot of stuff since then right until now.
<br/><br/>

My Side:
<br/><br/>
So now you know that sammko made a really dramatic story about this all. But here’s the reality: <b>we have no freaking clue what we’re doing.</b>  Now you may say, then why are you making this mod? Well, it’s fun we get things working but don’t always completly understand it all. We try to keep from messing up a ton by using git more, reviewing our code thouroughly, fixing bugs before adding features and keeping the world up to date. We want to find the problems, not to keep the users happy with new stuff.</p>