<h1>Energy Packets<span class="pull-right label label-warning">Work In Progress</span></h1>
<p>There are 5 types of energy packets, Empty, Gammatronium, Radium, Positronium, and Neutronium.</p>
<p>These act as the basic power system in QuantumCraft and can be used in different machines.</p>

<h3>Gammatronium EPacket</h3>
<p>Currently this is the only energy packet with a use which is used in the Quantum Gamma Infuser to create Gamm Infused Tools</p>

<h3>Radium EPacket</h3>
<p></p>

<h3>Positronium EPacket</h3>
<p></p>

<h3>Neutronium EPacket</h3>
<p></p>

<h3>Empty</h3>
<p>Empty EPackets are used in a Quantum Extractor for creating the other types of EPackets</p>
