
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <title><?php echo($page_title); ?> - <?php echo($site_name); ?></title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="">
      <meta name="author" content="">

      <!-- Le styles -->
      <link href="bs/css/bootstrap.min.css" rel="stylesheet">
      <link href="bs/css/bootstrap-responsive.min.css" rel="stylesheet">
      <link href="bs/css/main.css" rel="stylesheet">

      <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
        <script src="../assets/js/html5shiv.js"></script>
      <![endif]-->

      <!-- Fav and touch icons -->
      <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                      <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                     <link rel="shortcut icon" href="../assets/ico/favicon.png">
    </head>

    <body>

      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
             <a class="brand" href="index.php"><?php echo($site_name); ?></a>
            <div class="nav-collapse collapse">
              <ul class="nav">
                  <li <?php if($page == "home"){?> class="active" <?php } ?>><a href="index.php">Home</a></li>
                  <li <?php if($page == "about"){?> class="active" <?php } ?>><a href="?page=about">About</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>

      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span3">
            <div class="well sidebar-nav">
              <ul class="nav nav-list" data-spy="affix">
                <li class="nav-header">Machines</li>
                <li><a href="?page=qinfuser">Quantum Infuser</a></li>
                <li><a href="?page=qextractor">Quantum Extractor</a></li>
                <li class="nav-header">Items</li>
                <li><a href="?page=epackets">Energy Packets</a></li>
                <li><a href="?page=crystals">Crystals</a></li>
                <li><a href="?page=ctools">Crystal Tools</a></li>
                <li><a href="?page=gitools">Gamma Infused Tools</a></li>
                <li><a href="?page=cshard">Crystal Shard</a></li>
                <li><a href="?page=plutonium">Plutonium</a></li>
                <li class="nav-header">Blocks</li>
                <li><a href="?page=decoblocks">Decoration Blocks</a></li>
                <li><a href="?page=ores">Ores</a></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
      <div class="span9">