<h1>Ores<span class="pull-right label label-warning">Work in Progress</span></h1>
<p>There are 5 ores in this mod, Positronium, Gammatronium, Radium, Neutronium, Depleted, and Plutonium</p>

<div>
<h3>Positronium <img width="10%" height="10%" class="pull-right" src="img/render_POSI.png"></h3>
<p>Positronium is a blue ore that drops one positronium crystal when broken.</p><br/>
</div>
<div>
<h3>Gammatronium <img width="10%" height="10%" class="pull-right" src="img/render_GAMM.png"></h3>
<p>Gammatronium is green ore that drops one gammatronium crystal when broken.</p><br/>
</div>
<div>
<h3>Radium <img width="10%" height="10%" class="pull-right" src="img/render_RADI.png"></h3>
<p>Radium is red ore that drops one radium crystal when broken.</p><br/>
</div>
<div>
<h3>Neutronium <img width="10%" height="10%" class="pull-right" src="img/render_NEUT.png"></h3>
<p>Neutronium is yellow ore that drops one neutronium crystal when broken.</p><br/>
</div>
<div>
<h3>Depleted <img width="10%" height="10%" class="pull-right" src="img/render_DEPL.png"></h3>
<p>Depleted Ore is gray ore that drops one depleted crystal when broken.</p><br/>
</div>
<div>
<h3>Plutonium <img width="10%" height="10%" class="pull-right" src="img/render_PLUT.png"></h3>
<p>Plutonium is blue/gray ore that drops one plutonium ore when broken.</p><br/>
</div>