<h1>Ores<span class="pull-right label label-warning">Work in Progress</span></h1>
<p>There are 5 ores in this mod, Positronium, Gammatronium, Radium, Neutronium, and Plutonium</p>
<h3>Positronium</h3>
<img width="10%" height="10%" class="" src="img/render_POSI.png">
<p>Positronium is a blue ore that drops one positronium crystal when broken.
</p>

<h3>Gammatronium</h3>
<img width="10%" height="10%" class="" src="img/render_GAMM.png">
<p>Gammatronium is green ore that drops one gammatronium crystal when broken.</p>




