<h1>Quantum Extractor <img width="10%" height="10%" class="" src="img/render_EXTR.png"> <span class="pull-right label label-warning">Work in Progress</span></h1>

<p>The Quantum Extractor is a necessary tool in creating Energy Packets (EPs) which can power other machines. You can put any type of the crystals in the upper left slot and an empty energy packet in the lower left, with a little bit of fuel (either from IC2 or coal) you will get a filled up energy packet.</p>




