<h1>Quantum Infuser <img width="10%" height="10%" class="" src="img/render_INFS.png"> <span class="pull-right label label-warning">Work in Progress</span>
</h1>

<p>The Quantum Infuser is an important tool in creating bone crunching weapons that are infused with Gammatronium. This added radiation makes the mob attacked wither to its death.</p>

<p>It is a Tier 1 Machine that is used to infuse pure gamma energy into crystal tools. It works on the principle of Quantum infusion which is based on Quantum tunneling.</p>

